# Generated by Django 5.0.6 on 2024-07-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("country", models.CharField(max_length=64, verbose_name="страна")),
                ("city", models.CharField(max_length=64, verbose_name="город")),
                ("street", models.CharField(max_length=64, verbose_name="улица")),
                (
                    "building_number",
                    models.CharField(max_length=32, verbose_name="номер дома"),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="LinkOfChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название звена"),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="задолженность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="chain.contact",
                        verbose_name="контакты звена",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="поставщик",
                        to="chain.linkofchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="название продукта"),
                ),
                (
                    "model",
                    models.CharField(max_length=256, verbose_name="модель продукта"),
                ),
                ("market_date", models.DateField(verbose_name="дата выхода на рынок")),
                (
                    "link_of_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="chain.linkofchain",
                        verbose_name="звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
