# Generated by Django 5.0.6 on 2024-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("country", models.CharField(max_length=64, verbose_name="страна")),
                ("city", models.CharField(max_length=64, verbose_name="город")),
                ("street", models.CharField(max_length=64, verbose_name="улица")),
                (
                    "building_number",
                    models.CharField(max_length=32, verbose_name="номер дома"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название звена"),
                ),
            ],
        ),
    ]
