# Generated by Django 5.0.6 on 2024-07-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkofchain",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="поставщик",
                to="chain.linkofchain",
                verbose_name="связанное звено цепи",
            ),
        ),
    ]
