# Generated by Django 5.0.6 on 2024-07-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkofchain",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="задолженность"
            ),
        ),
        migrations.AlterField(
            model_name="linkofchain",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chain.linkofchain",
                verbose_name="связанное звено цепи",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="market_date",
            field=models.DateField(verbose_name="дата выхода на рынок"),
        ),
    ]
