# Generated by Django 5.0.6 on 2024-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="market_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="дата выхода на рынок"
            ),
        ),
    ]
